### ISSUE TITLE
465

### ISSUE THREAD

**Issue by DPG896** [HighestDreams/Emojis#4]
Update the plugin protocol, emoji plugin is here in this picture![Screenshot_20210922-083838.png](https://user-images.githubusercontent.com/82310008/134402961-cc1975f8-1383-4ae3-b60a-1b9fcb7b073d.png)

**Comment by HighestDreams** [comment]
Which version of pocket-mine you use? give me your protocol
For this, use these steps :

1. Run you pocket-mine server
2. Type command /ver
3. Now you can see your version & protocol, sent the info here to i fix the plugin.

**Comment by DPG896** [comment]
It's dev-2

**Comment by HighestDreams** [comment]
Plugin fixed, you can download from github right now or if you use aternos you need to wait until next aternos plugin update.

**Comment by DPG896** [comment]
Thanks a lot :)
